# This is some config for the ~/.bashrc
# If your want to used this, please use "cat bashr >> ~/.bashrc"

# set color
alias grep='grep --color=auto'

# set python use table
if [[ -f ~/.pystartup.py ]]; then
	export PYTHONSTARTUP=~/.pystartup.py
fi
